# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_LearningToGrow.ipynb.

# %% auto 0
__all__ = ['seed']

# %% ../nbs/01_LearningToGrow.ipynb 3
from .core import *
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
from tqdm import tqdm

# %% ../nbs/01_LearningToGrow.ipynb 8
seed = torch.zeros(1, 16, TARGET_SIZE, TARGET_SIZE).to(def_device)
seed[:, 3:, TARGET_SIZE//2, TARGET_SIZE//2] = 1.0
